package dev.sentinel.application;

import dev.sentinel.domain.config.SentinelException;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardOpenOption;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.stream.Stream;

/** Creates a conservative, user-owned ArchUnit test only when the project has none. */
public final class ArchitectureTestGenerator {
    private static final Pattern PACKAGE = Pattern.compile("\\bpackage\\s+([A-Za-z_][\\w.]*)\\s*;");

    public record TestChange(Path file, boolean created, String architecture) {
    }

    public TestChange generate(Path projectRoot, String architecture) {
        String basePackage = detectBasePackage(projectRoot);
        Path packageDirectory = projectRoot.resolve("src/test/java").resolve(basePackage.replace('.', '/'));
        Path test = packageDirectory.resolve("ArchitectureTest.java");
        if (Files.exists(test)) return new TestChange(test, false, architecture);
        String content = testSource(basePackage, architecture);
        try {
            Files.createDirectories(packageDirectory);
            Files.writeString(test, content, StandardOpenOption.CREATE_NEW, StandardOpenOption.WRITE);
            return new TestChange(test, true, architecture);
        } catch (java.nio.file.FileAlreadyExistsException e) {
            return new TestChange(test, false, architecture);
        } catch (IOException e) {
            throw new SentinelException("Could not generate ArchUnit test " + test + ": " + e.getMessage(), e);
        }
    }

    public void rollback(TestChange change) {
        if (change == null || !change.created()) return;
        try {
            Files.deleteIfExists(change.file());
        } catch (IOException e) {
            throw new SentinelException("Could not remove generated ArchUnit test " + change.file()
                    + ": " + e.getMessage(), e);
        }
    }

    private static String detectBasePackage(Path root) {
        Path source = root.resolve("src/main/java");
        if (Files.isDirectory(source)) {
            try (Stream<Path> files = Files.walk(source)) {
                for (Path file : files.filter(path -> path.toString().endsWith(".java")).toList()) {
                    Matcher matcher = PACKAGE.matcher(Files.readString(file));
                    if (matcher.find()) return matcher.group(1);
                }
            } catch (IOException e) {
                throw new SentinelException("Could not inspect Java packages: " + e.getMessage(), e);
            }
        }
        return "com.example";
    }

    private static String testSource(String basePackage, String architecture) {
        String rule = switch (architecture) {
            case "hexagonal" -> "noClasses().that().resideInAnyPackage(\"..domain..\", \"..application..\")"
                    + ".should().dependOnClassesThat().resideInAnyPackage(\"..adapter..\", \"..infrastructure..\")";
            case "clean" -> "noClasses().that().resideInAnyPackage(\"..domain..\", \"..core..\")"
                    + ".should().dependOnClassesThat().resideInAnyPackage(\"..controller..\", \"..adapter..\", \"..infrastructure..\")";
            default -> "noClasses().that().resideInAnyPackage(\"..controller..\")"
                    + ".should().dependOnClassesThat().resideInAnyPackage(\"..repository..\")";
        };
        return "package " + basePackage + ";\n\n"
                + "import com.tngtech.archunit.junit.AnalyzeClasses;\n"
                + "import com.tngtech.archunit.junit.ArchTest;\n"
                + "import static com.tngtech.archunit.lang.syntax.ArchRuleDefinition.noClasses;\n\n"
                + "// Generated by Sentinel for the " + architecture + " architecture.\n"
                + "@AnalyzeClasses(packages = \"" + basePackage + "\")\n"
                + "class ArchitectureTest {\n"
                + "    @ArchTest\n"
                + "    static final com.tngtech.archunit.lang.ArchRule architecture = " + rule + ";\n"
                + "}\n";
    }

}
